### ISSUE TITLE
Google fonts in ios throw error --`path_provider_foundation.podspec`

### ISSUE THREAD

**Issue by mghase** [material-foundation/flutter-packages#450] opened 2023-08-15 20:40 UTC
### Package

All packages

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Steps to reproduce:
1.
1.
1.

### Relevant log output

```shell
Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `path_provider_foundation` from `.symlinks/plugins/path_provider_foundation/darwin`
    [!] Failed to load 'path_provider_foundation' podspec: 
    [!] Invalid `path_provider_foundation.podspec` file: syntax error, unexpected <<
```

**Comment by guidezpl** [comment] 2024-02-26 14:25
Unable to reproduce locally. Without steps to reproduce the error, I have to close this issue for now.

**Closed by guidezpl** 2024-02-26 14:25 UTC
Labels: bug, p: google_fonts
