### ISSUE TITLE
Error: Type 'FontFeature' not found.

### ISSUE THREAD

**Issue by afradahsan** [material-foundation/flutter-packages#568] opened 2024-03-01 22:09 UTC
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
When I used google_fonts latest version 6.2.0 in my project i started facing this issue:

`/C:/Users/Dell/AppData/Local/Pub/Cache/hosted/pub.dev/google_fonts-6.2.0/lib/src/google_fonts_base.dart:69:8: Error: Type 'FontFeature' not found.
  List<FontFeature>? fontFeatures,`

then i tried downgrading the version, but that didn't seem to work, tried flutter clean and all. but, the issue persists.
When i removed the google fonts package, the app started working fine.

![image](https://github.com/material-foundation/flutter-packages/assets/139952097/acb290b7-c289-4e07-a356-c721331560ac)

Would be great if someone could suggest a solution.

```[tasklist]
### Tasks
```

**Comment by guidezpl** [comment] 2024-03-04 07:16
Closing as duplicate of https://github.com/material-foundation/flutter-packages/issues/567

**Closed by guidezpl** 2024-03-04 07:16 UTC
Labels: bug, triage

**Comment by Monish-Kumar-D** [comment] 2024-03-29 20:10
#567 
I encountered a similar error and resolved it by updating the `google_fonts` dependency in my `pubspec.yaml` file.

Initially, I had:

```yaml
google_fonts: ^6.1.0

However, this caused an error. I realized that it should be:

google_fonts: 6.1.0

By removing the caret symbol (^), it ensures that my project uses a compatible version equal to 6.1.0. This resolved the issue for me.

![fonterror](https://github.com/material-foundation/flutter-packages/assets/141710569/79e38e07-19fd-4039-8164-ca9c2d05f5de)

Hope this helps!

**Comment by Monish-Kumar-D** [comment] 2024-03-29 20:12
#567 
I encountered a similar error and resolved it by updating the `google_fonts` dependency in my `pubspec.yaml` file.

Initially, I had:

```yaml
google_fonts: ^6.1.0

However, this caused an error. I realized that it should be:

google_fonts: 6.1.0

By removing the caret symbol (^), it ensures that my project uses a compatible version equal to 6.1.0. This resolved the issue for me.

![fonterror](https://github.com/material-foundation/flutter-packages/assets/141710569/ce9bb5fb-b8d2-4b50-a33b-f87eb506f0c1)


Hope this helps!

**Comment by Monish-Kumar-D** [comment] 2024-03-29 20:18
#567 


I encountered a similar error and resolved it by updating the `google_fonts` dependency in my `pubspec.yaml` file.
![fonterror](https://github.com/material-foundation/flutter-packages/assets/141710569/125cc7ff-d67e-4d34-97b5-818ac570caea)

By removing the caret symbol (^), it ensures that my project uses a compatible version equal to 6.1.0. This resolved the issue for me.
Hope this helps!
Initially, I had:

```yaml
google_fonts: ^6.1.0


#However, this caused an error. I realized that it should be:
google_fonts: 6.1.0
