### ISSUE TITLE
miss font Noto Sans SC

### ISSUE THREAD

**Issue by magixyu** [material-foundation/flutter-packages#451] opened 2023-08-16 14:52 UTC
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
Noto Sans SC in the package.
https://fonts.google.com/noto/specimen/Noto+Sans+SC

## Steps to reproduce:
1.
1.
1.

### Relevant log output

```shell
NA-
```

**Comment by guidezpl** [comment] 2023-08-16 15:43
Duplicate of https://github.com/material-foundation/flutter-packages/issues/126

**Closed by guidezpl** 2023-08-16 15:42 UTC
Labels: bug, triage
