### ISSUE TITLE
Dynamic ColorScheme does not support new color tokens

### ISSUE THREAD

**Issue by emmaxCreative** [material-foundation/flutter-packages#591] opened 2024-05-28 10:47 UTC
### Package

dynamic_color

### Existing issue?

- [ ] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
Expected result: dynamic colorscheme should support the new color tokens: for example surfaceContainerHigh etc

Actual result: All components of flutter that probably use the new tokens under the hood use a fallback color which results in an UI where you can se no different shades from different levels of containers. For example a card will have the same color as the scaffold background. 

## Steps to reproduce:

1.  install Flutter 3.22.1
2. try to use dynamic theme

### Relevant log output

```shell
Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4412], locale de-DE)
    • Flutter version 3.22.1 on channel stable at C:\flutter               
    • Upstream repository https://github.com/flutter/flutter.git           
    • Framework revision a14f74ff3a (6 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b                                           
    • Dart version 3.4.1                                                   
    • DevTools version 2.34.3
```

**Comment by Henry-Hiles** [comment] 2024-06-09 18:33
I'm not sure if you have permission but it needs the "p: dynamic_color" plugin

**Comment by tmaihoff** [comment] 2024-06-16 17:05
Running into the same issue after upgrading to Flutter 3.22.
Do you we have a timeline on this?

**Comment by purofle** [comment] 2024-06-20 12:00
Same problem on Flutter 3.22

**Comment by guidezpl** [comment] 2024-07-02 12:06
Closing as dupe of #582

**Closed by guidezpl** 2024-07-02 12:06 UTC
Labels: bug, p: dynamic_color
