### ISSUE TITLE
Unable to load fonts when running widget tests

### ISSUE THREAD

**Issue by RishabJaiswal** [material-foundation/flutter-packages#439] opened 2023-07-06 04:41 UTC
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
I don't want to include font files in my release bundle, hence only relying in the downloadable nature of the fonts but the test log is getting polluted throwing exceptions that the test failed to load.

![image](https://github.com/material-foundation/flutter-packages/assets/10057450/1494052b-81f9-4c19-ba8b-e6bf7b73c4f2)

## Steps to reproduce:
1. Create a widget that uses downloadable `google_font`
2. **Do not** include font files in `assets` or `google_fonts`
3. Create a widget test for the widget in step
4. Run the widget test. The exception in above screen shot is thrown.

Using `google_fonts: 4.0.3`

### Relevant log output

```shell
Error: google_fonts was unable to load font SourceSansPro-SemiBold because the following exception occurred:
Exception: Failed to load font with url: https://fonts.gstatic.com/s/a/918213748bccf07ee3b20ed95cc824bb329b9b048732700e32c241bba63a029b.ttf

There is likely something wrong with your test. Please see https://github.com/material-foundation/flutter-packages/blob/main/packages/google_fonts/example/test for examples of how to test with google_fonts.
If troubleshooting doesn't solve the problem, please file an issue at https://github.com/material-foundation/flutter-packages/issues/new/choose.

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown running a test (but after the test had completed):
Exception: Failed to load font with url:
https://fonts.gstatic.com/s/a/918213748bccf07ee3b20ed95cc824bb329b9b048732700e32c241bba63a029b.ttf

When the exception was thrown, this was the stack:
#0      _httpFetchFontAndSaveToDevice (package:google_fonts/src/google_fonts_base.dart:274:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

**Comment by BetoMottu** [comment] 2023-08-07 13:52
we have the same error, using version 4.0.4

![image](https://github.com/material-foundation/flutter-packages/assets/102568899/f6d6141e-6dd9-4e87-b608-f1aa2c57c635)

**Comment by guidezpl** [comment] 2023-08-09 11:45
The original issue regards tests (see the README and its links for working test examples).

@BetoMottu if you have end users facing this issue, than your app doesn't seem to have the correct permissions. The error includes a link pointing you to resources to properly set your apps' access to the internet.

**Comment by BetoMottu** [comment] 2023-08-09 18:00
@guidezpl, before declaring the problem we check all permissions, as the problem seems to have something to do with connection permission. Our application uses this lib since the beginning of the project a little over 1 year, apparently the problem occurred after the update from version 3.0.1 to 4.0.4, previously we didn't have this problem. Analyzing the issues of this project I found something that is also related to our project, and that could be related to the problem. We used the Poppins font and another report was made with a similar problem: https://github.com/material-foundation/flutter-packages/issues/441

As you can see below, only the source link is available for download, without a link to deal with the problem:

![image](https://github.com/material-foundation/flutter-packages/assets/102568899/980c42e6-e314-4b10-bc76-37c5dd82ce32)

We keep getting the error, we are investigating on our side.

**Comment by guidezpl** [comment] 2023-08-10 07:32
https://fonts.gstatic.com/s/a/9ecfd020e9cc0b676025df8390c0dc8cc2062523540887dd04bec0ef4d5a449c.ttf is a valid link, so please double check permissions, https://docs.flutter.dev/data-and-backend/networking

**Comment by cybex-dev** [comment] 2023-09-19 18:10
Experiencing the same issue, Android specifically

> https://fonts.gstatic.com/s/a/9ecfd020e9cc0b676025df8390c0dc8cc2062523540887dd04bec0ef4d5a449c.ttf is a valid link, so please double check permissions, https://docs.flutter.dev/data-and-backend/networking

According to [Data and Backend > Networking](https://docs.flutter.dev/data-and-backend/networking#platform-notes), 
> Android apps must [declare their use of the internet](https://developer.android.com/training/basics/network-ops/connecting) in the Android manifest (AndroidManifest.xml )

We have this included and have had for a while however issue persists. Based on affected users, it affects a handful possibly indicating network connectivity issues. I'd still like to contribute this issue to the discussion.
![image](https://github.com/material-foundation/flutter-packages/assets/29998700/0b84a447-720b-401a-a02b-402f4e2d8739)

**Comment by guidezpl** [comment] 2023-09-20 06:49
@cybex-dev thanks for checking, are there multiple `AndroidManifest.xml` files?

**Comment by cybex-dev** [comment] 2023-09-20 12:46
> @cybex-dev thanks for checking, are there multiple `AndroidManifest.xml` files?

None extra other than the 3 standard build variation manifests in `src/debug, src/main, src/profile` all which contain:
```xml
<uses-permission android:name="android.permission.INTERNET"/>
```

**Comment by cybex-dev** [comment] 2023-09-20 12:49
I ended up using the local caching solution by providing desired fonts in the `google_fonts/` assets directory, see [this solution](https://stackoverflow.com/a/74950369) for details if anyone is interested.

**Comment by guidezpl** [comment] 2024-02-26 14:23
Since we have working unit and widget tests in packages/google_fonts/test, I'm considering this issue unreproducible and will therefore close it. If this changes, or if you have an idea for improving the existing tests to cover your case, please reopen this issue

**Closed by guidezpl** 2024-02-26 14:23 UTC
Labels: bug, waiting for developer response, p: google_fonts
