### ISSUE TITLE
RuntimeError: memory access out of bounds, on web/canvaskit

### ISSUE THREAD

**Issue by sgehrman** [material-foundation/flutter-packages#399] opened 2023-05-02 03:31 UTC
### Package

google_fonts

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:
I have a "choose font" list view of every google font.  It's worked for years, not sure when it started crashing. I don't test it much recently.  But it's crashing now.

## Steps to reproduce:
Make a listview and display the font name using the the style GoogleFonts.getFont(fontName, textStyle: textStyle)

scroll down, it works for the first 50 or so, then crashes.

### Relevant log output

```shell
caught RuntimeError: memory access out of bounds
    at canvaskit.wasm:0xbcac
    at canvaskit.wasm:0x89ac
    at canvaskit.wasm:0x572cf
    at canvaskit.wasm:0x486e0a
    at canvaskit.wasm:0xf4aac
    at Function._MakeFreeTypeFaceFromData (canvaskit.js:182:52)
    at a.Typeface.MakeFreeTypeFaceFromData (canvaskit.js:92:194)
    at e.TypefaceFontProvider.registerFont (canvaskit.js:82:512)
    at Yd.a5l (main.dart.js:48453:5)
    at main.dart.js:48460:3
caught RuntimeError: memory access out of bounds
    at canvaskit.wasm:0xc0ab
    at v (canvaskit.js:26:398)
    at a.Typeface.MakeFreeTypeFaceFromData (canvaskit.js:92:160)
    at main.dart.js:48458:50
    at bJE.a (main.dart.js:4883:62)
    at bJE.$2 (main.dart.js:57235:14)
    at Object.y (main.dart.js:4869:10)
    at Yd.aWy (main.dart.js:48463:10)
    at Yd.V7 (main.dart.js:48455:21)
    at main.dart.js:8199:25
```

**Comment by guidezpl** [comment] 2023-05-03 08:20
Thanks for filing an issue. Please provide a self-contained code sample

**Comment by sgehrman** [comment] 2023-06-08 09:39
Here it is.  Please fix as it's important for my app.

https://github.com/sgehrman/font_bugz

**Comment by sgehrman** [comment] 2023-06-08 09:42
![Screenshot-20230608024138-2640x1535](https://github.com/material-foundation/flutter-packages/assets/287137/a9985cb4-cc07-44ca-9d9d-cda40593aaa5)

**Comment by guidezpl** [comment] 2023-06-08 10:18
This would be expected since you're attempting to download and load hundreds of fonts. Since the package is working as intended, I'll close this issue. Please look for help from the community (e.g. Discord, StackOverflow)

**Closed by guidezpl** 2023-06-08 10:18 UTC
Labels: bug, waiting for developer response, p: google_fonts

**Comment by sgehrman** [comment] 2023-11-12 12:17
Expected?  What do you think my users expect?  I'm shipping real apps, not demos.
