### ISSUE TITLE
`dynamic_color` on `Android`: Please migrate `CorePalette` to Flutter 3.22

### ISSUE THREAD

**Issue by twinstar6980** [material-foundation/flutter-packages#590] opened 2024-05-20 14:57 UTC
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Expected vs actual result:

[Flutter 3.22](https://docs.flutter.dev/release/breaking-changes/new-color-scheme-roles) has updated `ColorScheme`. The new `ColorScheme` includes a variety of surfaceContainer colors. Using the current version of `dynamic_color` in 3.22 projects will cause the background colors of some widgets to be difficult to distinguish.

In the example below, the app uses `surface` as the background color, and BottomAppBar uses `surfaceContainer` as the background color by default. The first one is the color created by 3.22 ColorScheme.fromSeed, and the second one is using `getCorePalette().toColorScheme()`.

<img width="336" alt="2" src="https://github.com/material-foundation/flutter-packages/assets/37923060/16abd933-6e42-4b44-ba9c-16c05c98b509">
<img width="336" alt="1" src="https://github.com/material-foundation/flutter-packages/assets/37923060/d59b3e5f-229a-404c-9e55-af88e466ea06">

**Comment by resucutie** [comment] 2024-05-22 14:07
Duplicate of #582

**Closed** 2024-05-22 14:10 UTC
